import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased py-4 px-16`}
      >
        <div className="flex">
          <h1 className="text-xl tracking-[3px] uppercase">SpaceLance</h1>
          <div className="w-fit bg-[#222222] flex justify-around gap-8 mx-auto text px-4 py-3 rounded-xl font-semibold">
            <button>Home</button>
            <button>Services</button>
            <button>Projects</button>
            <button>Contact</button>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
